logs:
    - name: root
      level: info
      formatter: '%d%T%m%n'
      appenders:
          - type: FileLogAppender
            file: /home/hangzhang/projects/root.txt
          - type: StdoutLogAppender
    - name: system
      level: info
      formatter: '%d%T%m%n'
      appenders:
          - type: FileLogAppender
            file: /home/hangzhang/projects/system.txt
          - type: StdoutLogAppender

system:
    port: 9090
    value: 15
    # int_vector: [[10, 20, 30], [11, 22, 33]] # error class LexicalCast<std::string, std::vector<T> > 从这个定义可以看出，只支持一维vector ，类型T 其实这里指的就是 一个YAML::Node
                                             # class LexicalCast<std::string, std::vector<std::vector<T> > > maybe can support it
    int_vector: [10, 20, 30]  # right
    #int_vector:                 # error
    #    vector1: [11, 22, 33]
    #    vector2: [101, 202, 303]
